from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter
import re


def get_video_id(url):
    # Extracts video ID from URL
    match = re.search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url)
    if match:
        return match.group(1)
    else:
        raise ValueError("Invalid YouTube URL")


def fetch_transcript(video_url, lang="en"):
    video_id = get_video_id(video_url)
    ytt = YouTubeTranscriptApi()
    transcript_list = ytt.list(video_id)

    # IF available it gets them, or else it will get the auto generate one
    try:
        transcript = transcript_list.find_manually_created_transcript([lang])
    except:
        transcript = transcript_list.find_transcript([lang])

    # print(
    #     transcript.video_id,
    #     transcript.language,
    #     transcript.language_code,
    #     # whether it has been manually created or generated by YouTube
    #     transcript.is_generated,
    #     # whether this transcript can be translated or not
    #     transcript.is_translatable,
    #     # a list of languages the transcript can be translated to
    #     transcript.translation_languages,
    # )

    formatter = TextFormatter()
    text_transcript = formatter.format_transcript(transcript.fetch())

    return text_transcript


# Example usage
# video_url = input("Enter YouTube video URL: ")
# transcript_text = fetch_transcript(video_url)
# title = get_video_id(video_url)
# with open(f"{title}.txt", "w", encoding="utf-8") as f:
#     f.write(transcript_text)
# print(f"Transcript saved to {title}.txt")
